apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
  labels:
    app: frontend
data:
  VUE_APP_CATEGORY_SERVICE_URL: "http://157.230.195.62/api/categories"
  VUE_APP_PRODUCT_SERVICE_URL: "http://157.230.195.62/api/products"
  VUE_APP_REVIEW_SERVICE_URL: "http://157.230.195.62/api/reviews"
  
  # Configuration flags
  VUE_APP_USE_MOCK: "false"
  
  # Additional configuration options
  VUE_APP_LOG_LEVEL: "error"
  VUE_APP_PAGINATION_LIMIT: "20"