apiVersion: v1
kind: ConfigMap
metadata:
  namespace: category-service
  name: category-config
  labels:
    app: category-service
data:
  PORT: "3000"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  
  # MongoDB connection information
  MONGODB_HOST: "mongodb.category-service.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "category-db"
  MONGODB_URI: "mongodb://mongodb.category-service.svc.cluster.local:27017/category-db"
  
  # Additional configuration options
  ENABLE_METRICS: "true"
  RATE_LIMIT_WINDOW_MS: "60000"  # 1 minute
  RATE_LIMIT_MAX: "100"  # 100 requests per minute
  CORS_ENABLED: "true"
  ALLOWED_ORIGINS: "*"