apiVersion: v1
kind: ConfigMap
metadata:
  namespace: product-service
  name: product-config
  labels:
    app: product-service
data:
  CATEGORY_SERVICE_URL: "http://category-service.category-service.svc.cluster.local:3000"
  DB_HOST: "mysql.product-service.svc.cluster.local"
  DB_DATABASE: "product_db"
  DB_USERNAME: "root"
  # You can also add other non-sensitive configuration here
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
  MAX_CONNECTIONS: "100"