apiVersion: v1
kind: ConfigMap
metadata:
  namespace: review-service
  name: review-config
  labels:
    app: review-service
data:
  # Service connection
  PRODUCT_SERVICE_URL: "http://product-service.product-service.svc.cluster.local"
  
  # Flask configuration
  FLASK_APP: "app"
  FLASK_ENV: "production"
  PORT: "5000"
  
  # Database configuration
  DB_HOST: "postgres.review-service.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "review_db"
  DB_USER: "postgres"
  
  # Full database connection string
  # Note: In a production environment, you would typically store connection strings with 
  # credentials in a Secret. Moving it to ConfigMap is typically only done when there are
  # no sensitive credentials or for development environments.
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres:password@postgres/review_db"
  
  # Application settings
  LOG_LEVEL: "info"
  PAGINATION_LIMIT: "20"
  ENABLE_METRICS: "true"
  CORS_ENABLED: "true"
  ALLOWED_ORIGINS: "*"