apiVersion: v1
kind: Secret
metadata:
  namespace: review-service
  name: review-db-secret
  labels:
    app: review-service
type: Opaque
data:
  # These are placeholder credentials for future use if you decide to separate sensitive info
  db_password: cGFzc3dvcmQ=  # 'password' base64 encoded
  
  # Add any other secrets here if needed
  # api_key: YXBpLWtleS12YWx1ZQ==  # 'api-key-value' base64 encoded
  # jwt_secret: and0LXNlY3JldC1rZXk=  # 'jwt-secret-key' base64 encoded