# OpenTelemetry Collector Helm Values
# https://github.com/open-telemetry/opentelemetry-helm-charts

mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.87.0"

# Resource limits for 2 vCPU, 4GB RAM nodes
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

config:
  receivers:
    # OTLP receiver for traces and logs
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    # Memory limiter to prevent OOM
    memory_limiter:
      check_interval: 1s
      limit_mib: 400
      spike_limit_mib: 100
    
    # Batch processor for better performance
    batch:
      timeout: 10s
      send_batch_size: 1024

  exporters:
    # Export logs to OpenSearch (using elasticsearch exporter)
    elasticsearch:
      endpoints: ["http://opensearch-cluster-master.opensearch.svc.cluster.local:9200"]
      logs_index: "otel-logs"
      traces_index: "otel-traces"
    
    # Debug exporter to see what's being received
    debug:
      verbosity: detailed

  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [elasticsearch, debug]
      
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [elasticsearch, debug]

# Pod annotations for scraping
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8888"
  prometheus.io/path: "/metrics"