apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-collector
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-collector
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/stats", "pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-collector
subjects:
- kind: ServiceAccount
  name: metrics-collector
  namespace: observability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-collector-config
  namespace: observability
data:
  config.yaml: |
    receivers:
      kubeletstats:
        collection_interval: 30s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_IP}:10250"
        insecure_skip_verify: true
        metric_groups:
          - pod
          - container
    
    processors:
      batch:
        send_batch_size: 512
        timeout: 5s
    
    exporters:
      otlp:
        endpoint: "signoz-otel-collector.observability.svc.cluster.local:4317"
        tls:
          insecure: true
    
    service:
      pipelines:
        metrics:
          receivers: [kubeletstats]
          processors: [batch]
          exporters: [otlp]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-collector
  namespace: observability
  labels:
    app: metrics-collector
spec:
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      serviceAccountName: metrics-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.111.0
        command:
          - "/otelcol-contrib"
          - "--config=/etc/otelcol-contrib/config.yaml"
        env:
        - name: K8S_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-vol
          mountPath: /etc/otelcol-contrib
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
      volumes:
      - name: config-vol
        configMap:
          name: metrics-collector-config
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet