apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
  labels:
    app: frontend
data:
  # Replace with the actual URL
  VUE_APP_CATEGORY_SERVICE_URL: "http://137.184.251.104:8000/category"
  VUE_APP_PRODUCT_SERVICE_URL: "http://137.184.251.104:8000/product"
  VUE_APP_REVIEW_SERVICE_URL: "http://137.184.251.104:8000/review"
  
  # Configuration flags
  VUE_APP_USE_MOCK: "false"
  
  # Additional configuration options
  VUE_APP_LOG_LEVEL: "error"
  VUE_APP_PAGINATION_LIMIT: "20"