apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laravel-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: laravel-project
  source:
    repoURL: https://github.com/einarr2o12/testing-microservices
    targetRevision: HEAD
    path: kubernetes/laravel-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates