version: '3.8'

services:
  # PostgreSQL Database for Review Service
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=review_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Review Service
  review-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:password@postgres/review_db
      - PRODUCT_SERVICE_URL=http://mockserver:1080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
    command: >
      sh -c "python -m flask --app app run --host=0.0.0.0 --port=5000 --debug"

  # Mock Server for Product Service API
  mockserver:
    image: mockserver/mockserver:latest
    ports:
      - "1080:1080"
    environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
    volumes:
      - ./mockserver:/config

volumes:
  postgres-data: