apiVersion: v1
kind: ConfigMap
metadata:
  namespace: laravel-app
  name: laravel-config
  labels:
    app: laravel-app
data:
  APP_NAME: "Laravel Monolithic App"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_TIMEZONE: "UTC"
  APP_URL: "http://localhost"
  
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgresql"
  DB_PORT: "5432"
  DB_DATABASE: "laravel-app"
  DB_USERNAME: "postgres"
  
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"
  
  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  
  CACHE_STORE: "database"
  QUEUE_CONNECTION: "database"
  
  # Application settings
  ENABLE_METRICS: "true"
  MAX_CONNECTIONS: "100"