apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: laravel-app
  name: laravel-deployment
  labels:
    app: laravel-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
      version: v1
  template:
    metadata:
      labels:
        app: laravel-app
        version: v1
    spec:
      initContainers:
      - name: copy-laravel-files
        image: 1911997/laravel-app:v1.1
        command: ['sh', '-c', 'cp -r /var/www/html/* /shared/ && chown -R 82:82 /shared/storage /shared/bootstrap/cache && chmod -R 775 /shared/storage /shared/bootstrap/cache && env | grep -E "^(APP_|DB_|LOG_|SESSION_|CACHE_|QUEUE_|ENABLE_|MAX_)" | sed "s/^\\([^=]*\\)=\\(.*\\)/\\1=\"\\2\"/" > /shared/.env']
        volumeMounts:
        - name: laravel-files
          mountPath: /shared
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secret
              key: db-password
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secret
              key: app-key
      containers:
      - name: laravel-app
        image: 1911997/laravel-app:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: php-fpm
        volumeMounts:
        - name: laravel-files
          mountPath: /var/www/html
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-secret
              key: db-password
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: laravel-secret
              key: app-key
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: laravel-files
          mountPath: /var/www/html
        resources:
          limits:
            cpu: "0.2"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: laravel-files
        emptyDir: {}