apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: laravel-secret
  labels:
    app: laravel-app
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  # APP_KEY (base64 encoded Laravel key)
  app-key: YmFzZTY0OmkxOEdJTklLOVdPQTI5UUtaQ0g4eXl4VVVTNTZlUUNSZTJGbzRBTTB4RkE9
  # DB_PASSWORD (base64 encoded)
  db-password: cGFzc3dvcmQ=