apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: laravel-service
  labels:
    app: laravel-app
    service: laravel-service
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: laravel-app
  type: ClusterIP