name: Category Service CI

on:
  push:
    paths:
      - 'services/Backend/category/**'
      - '.github/workflows/category-service.yml'
    branches:
      - main
      - develop
    tags:
      - 'category-v*'
  pull_request:
    paths:
      - 'services/Backend/category/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: 1911997/category-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: services/Backend/category/package.json

    - name: Install dependencies
      working-directory: services/Backend/category
      run: npm ci

    - name: Run tests
      working-directory: services/Backend/category
      run: npm test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=sha,prefix=sha-

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: services/Backend/category
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update Kubernetes deployment
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -E "sha-[a-f0-9]+" | head -1 | cut -d':' -f2)
        sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${IMAGE_TAG}|g" kubernetes/category/deployment.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kubernetes/category/deployment.yaml
        git diff --staged --quiet || git commit -m "Update category service image to ${IMAGE_TAG}"
        git push