name: Product Service CI

on:
  push:
    paths:
      - 'services/Backend/product/**'
      - '.github/workflows/product-service.yml'
    branches:
      - main
      - develop
    tags:
      - 'product-v*'
  pull_request:
    paths:
      - 'services/Backend/product/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: 1911997/product-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql
        coverage: xdebug

    - name: Get composer cache directory
      id: composer-cache
      working-directory: services/Backend/product
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      working-directory: services/Backend/product
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run tests
      working-directory: services/Backend/product
      run: ./test.sh

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=sha,prefix=sha-

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: services/Backend/product
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update Kubernetes deployment
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -E "sha-[a-f0-9]+" | head -1 | cut -d':' -f2)
        sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${IMAGE_TAG}|g" kubernetes/product/deployment.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kubernetes/product/deployment.yaml
        git diff --staged --quiet || git commit -m "Update product service image to ${IMAGE_TAG}"
        git push