name: Review Service CI

on:
  push:
    paths:
      - 'services/Backend/review/**'
      - '.github/workflows/review-service.yml'
    branches:
      - main
      - develop
    tags:
      - 'review-v*'
  pull_request:
    paths:
      - 'services/Backend/review/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: 1911997/review-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      working-directory: services/Backend/review
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      working-directory: services/Backend/review
      run: echo "No tests configured for Python service"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=ref,event=tag
          type=sha,prefix=sha-

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: services/Backend/review
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Update Kubernetes deployment
      if: github.ref == 'refs/heads/main'
      run: |
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | grep -E "sha-[a-f0-9]+" | head -1 | cut -d':' -f2)
        sed -i "s|image: ${{ env.IMAGE_NAME }}:.*|image: ${{ env.IMAGE_NAME }}:${IMAGE_TAG}|g" kubernetes/review/deployment.yaml
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add kubernetes/review/deployment.yaml
        git diff --staged --quiet || git commit -m "Update review service image to ${IMAGE_TAG}"
        git push